### ISSUE TITLE
overflow when computing Ehrhart series

### ISSUE THREAD

**Issue by sophiasage** [Normaliz/PyNormaliz#102]
I was trying to compute the Ehrhart series of a four dimensional lattice polytope with 70 vertices in R^5 and backend='normaliz', and I received an overflow error. I was running sage 9.0 with pynormaliz installed. Any suggestions, or additional information that I should provide? 
```
Traceback (most recent call last):                                                                                                             
  File "/home/sophiae56/sage/SageMath/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap                                 
    self.run()                                                                                                                                 
  File "/home/sophiae56/sage/SageMath/local/lib/python3.7/multiprocessing/process.py", line 99, in run                                         
    self._target(*self._args, **self._kwargs)                                                                                                  
  File "/home/sophiae56/polynomials_of_polytropes/hstarcomp.py", line 104, in comparison                                                       
    univ = P.ehrhart_series().numerator()                                                                                                      
  File "/home/sophiae56/sage/SageMath/local/lib/python3.7/site-packages/sage/geometry/polyhedron/backend_normaliz.py", line 1407, in ehrhart_se
ries                                                                                                                                           
    e = self._nmz_result(cone, "EhrhartSeries")                                                                                                
  File "/home/sophiae56/sage/SageMath/local/lib/python3.7/site-packages/sage/geometry/polyhedron/backend_normaliz.py", line 283, in _nmz_result
    NumberfieldElementHandler=nfelem_handler)                                                                                                  
PyNormaliz_cpp.NormalizError: Could not convert 105930007655674189680.                                                                         
Overflow detected. A fatal size excess or  a computation overflow.                                                                             
 If Normaliz has terminated and you are using LongLong, rerun without it.                        
```

**Comment by w-bruns** [comment]
Please include the data defining your polytope or cone. Without it, it is difficult to say what is going on.

A potential explanation: the degree of the numerator of the Ehrhart series exceeds 32 bit (~ 10^10). At present this is an absolute barrier.

**Comment by w-bruns** [comment]
The next version of Normaliz will give more precise information on the reason of the overflow.

**Comment by jplab** [comment]
> Please include the data defining your polytope or cone. Without it, it is difficult to say what is going on.
> 
> A potential explanation: the degree of the numerator of the Ehrhart series exceeds 32 bit (~ 10^10). At present this is an absolute barrier.

To obtain the information of the normaliz cone in sage, type:

`sage: print(your_polytope._normaliz_format(c._get_nmzcone_data()))`

and write the output here.

**Comment by w-bruns** [comment]
I am no longer sure about my potential explanation. The reason given there should result in a different error message. Again: without the input to Normaliz one cannot say something reasonable.

**Comment by sophiasage** [comment]
Thank you for your reply! 

Here is one of the polytopes where I have this problem. I am actually starting with a rational polytope and first dilating it to have integer vertices. I should say a disclaimer that when I got that error, I was computing the Ehrhart series for many polytopes on a cluster, and when I try to reproduce it for a single polytope on my computer, it just doesn't finish.
```
sage: polytrope
[[1504, 1246, 1300, 1285, 936],
 [664, 1246, 310, 472, 936],
 [867, 1246, 513, 472, 936],
 [395, 125, 440, 0, 936],
 [1504, 1246, 1150, 1285, 936],
 [1504, 1234, 1150, 1109, 936],
 [1255, 985, 1300, 860, 936],
 [1504, 1234, 1300, 1109, 936],
 [1504, 1234, 1150, 1285, 936],
 [1504, 1234, 1300, 1285, 936],
 [867, 1246, 912, 472, 936],
 [1504, 1246, 1300, 1109, 936],
 [1255, 1246, 1300, 860, 936],
 [1504, 1246, 1150, 1109, 936],
 [604, 1186, 250, 412, 936],
 [1251, 981, 897, 1285, 936],
 [1251, 1246, 897, 1285, 936],
 [664, 1246, 310, 698, 936],
 [604, 1186, 250, 638, 936],
 [604, 334, 250, 638, 936],
 [604, 334, 250, 209, 936],
 [395, 125, 250, 0, 936],
 [604, 983, 250, 209, 936],
 [395, 774, 250, 0, 936],
 [845, 575, 1300, 1285, 936],
 [619, 349, 897, 1285, 936],
 [395, 774, 440, 0, 936],
 [619, 349, 1074, 1285, 936],
 [347, 77, 802, 1013, 936],
 [347, 77, 625, 1013, 936],
 [347, 77, 250, 0, 936],
 [347, 77, 250, 638, 936],
 [347, 77, 802, 362, 936],
 [-162, 774, 440, 0, 936],
 [-162, 774, 250, 0, 936],
 [347, 77, 440, 0, 936],
 [250, 1186, 250, 638, 936],
 [310, 1246, 310, 472, 936],
 [310, 1246, 912, 472, 936],
 [310, 1246, 310, 698, 936],
 [250, 1186, 250, 412, 936],
 [845, 575, 1300, 860, 936],
 [364, 1246, 1300, 860, 936],
 [571, 349, 897, 1285, 936],
 [364, 575, 1300, 860, 936],
 [310, 1246, 1246, 806, 936],
 [-134, 77, 802, 362, 936],
 [571, 575, 1300, 1285, 936],
 [571, 1246, 897, 1285, 936],
 [571, 1246, 1300, 1285, 936],
 [299, 77, 802, 1013, 936],
 [-134, 77, 802, 580, 936],
 [310, 1246, 1246, 1024, 936],
 [364, 575, 1300, 1078, 936],
 [299, 77, 625, 1013, 936],
 [364, 1246, 1300, 1078, 936],
 [310, 1246, 636, 1024, 936],
 [-76, 860, 250, 638, 936],
 [571, 349, 1074, 1285, 936],
 [-76, 77, 250, 638, 936],
 [-314, 77, 250, 400, 936],
 [-314, 622, 250, 400, 936],
 [-314, 622, 622, 400, 936],
 [-314, 77, 622, 400, 936],
 [-314, 77, 622, 182, 936],
 [-314, 622, 622, 182, 936],
 [-314, 77, 250, 0, 936],
 [-314, 622, 440, 0, 936],
 [-314, 622, 250, 0, 936],
 [-314, 77, 440, 0, 936]]
sage: p = Polyhedron(vertices = polytrope, backend = 'normaliz')
sage: p
A 4-dimensional polyhedron in QQ^5 defined as the convex hull of 70 vertices
sage: p.ehrhart_series()
```
Originally, the polytope was this rational polytope, but it is still not finishing:
```
sage: polytrope
[[1, 188/129, 623/516, 325/258, 1285/1032, 39/43],
 [1, 83/129, 623/516, 155/516, 59/129, 39/43],
 [1, 289/344, 623/516, 171/344, 59/129, 39/43],
 [1, 395/1032, 125/1032, 55/129, 0, 39/43],
 [1, 188/129, 623/516, 575/516, 1285/1032, 39/43],
 [1, 188/129, 617/516, 575/516, 1109/1032, 39/43],
 [1, 1255/1032, 985/1032, 325/258, 5/6, 39/43],
 [1, 188/129, 617/516, 325/258, 1109/1032, 39/43],
 [1, 188/129, 617/516, 575/516, 1285/1032, 39/43],
 [1, 188/129, 617/516, 325/258, 1285/1032, 39/43],
 [1, 289/344, 623/516, 38/43, 59/129, 39/43],
 [1, 188/129, 623/516, 325/258, 1109/1032, 39/43],
 [1, 1255/1032, 623/516, 325/258, 5/6, 39/43],
 [1, 188/129, 623/516, 575/516, 1109/1032, 39/43],
 [1, 151/258, 593/516, 125/516, 103/258, 39/43],
 [1, 417/344, 327/344, 299/344, 1285/1032, 39/43],
 [1, 417/344, 623/516, 299/344, 1285/1032, 39/43],
 [1, 83/129, 623/516, 155/516, 349/516, 39/43],
 [1, 151/258, 593/516, 125/516, 319/516, 39/43],
 [1, 151/258, 167/516, 125/516, 319/516, 39/43],
 [1, 151/258, 167/516, 125/516, 209/1032, 39/43],
 [1, 395/1032, 125/1032, 125/516, 0, 39/43],
 [1, 151/258, 983/1032, 125/516, 209/1032, 39/43],
 [1, 395/1032, 3/4, 125/516, 0, 39/43],
 [1, 845/1032, 575/1032, 325/258, 1285/1032, 39/43],
 [1, 619/1032, 349/1032, 299/344, 1285/1032, 39/43],
 [1, 395/1032, 3/4, 55/129, 0, 39/43],
 [1, 619/1032, 349/1032, 179/172, 1285/1032, 39/43],
 [1, 347/1032, 77/1032, 401/516, 1013/1032, 39/43],
 [1, 347/1032, 77/1032, 625/1032, 1013/1032, 39/43],
 [1, 347/1032, 77/1032, 125/516, 0, 39/43],
 [1, 347/1032, 77/1032, 125/516, 319/516, 39/43],
 [1, 347/1032, 77/1032, 401/516, 181/516, 39/43],
 [1, -27/172, 3/4, 55/129, 0, 39/43],
 [1, -27/172, 3/4, 125/516, 0, 39/43],
 [1, 347/1032, 77/1032, 55/129, 0, 39/43],
 [1, 125/516, 593/516, 125/516, 319/516, 39/43],
 [1, 155/516, 623/516, 155/516, 59/129, 39/43],
 [1, 155/516, 623/516, 38/43, 59/129, 39/43],
 [1, 155/516, 623/516, 155/516, 349/516, 39/43],
 [1, 125/516, 593/516, 125/516, 103/258, 39/43],
 [1, 845/1032, 575/1032, 325/258, 5/6, 39/43],
 [1, 91/258, 623/516, 325/258, 5/6, 39/43],
 [1, 571/1032, 349/1032, 299/344, 1285/1032, 39/43],
 [1, 91/258, 575/1032, 325/258, 5/6, 39/43],
 [1, 155/516, 623/516, 623/516, 403/516, 39/43],
 [1, -67/516, 77/1032, 401/516, 181/516, 39/43],
 [1, 571/1032, 575/1032, 325/258, 1285/1032, 39/43],
 [1, 571/1032, 623/516, 299/344, 1285/1032, 39/43],
 [1, 571/1032, 623/516, 325/258, 1285/1032, 39/43],
 [1, 299/1032, 77/1032, 401/516, 1013/1032, 39/43],
 [1, -67/516, 77/1032, 401/516, 145/258, 39/43],
 [1, 155/516, 623/516, 623/516, 128/129, 39/43],
 [1, 91/258, 575/1032, 325/258, 539/516, 39/43],
 [1, 299/1032, 77/1032, 625/1032, 1013/1032, 39/43],
 [1, 91/258, 623/516, 325/258, 539/516, 39/43],
 [1, 155/516, 623/516, 53/86, 128/129, 39/43],
 [1, -19/258, 5/6, 125/516, 319/516, 39/43],
 [1, 571/1032, 349/1032, 179/172, 1285/1032, 39/43],
 [1, -19/258, 77/1032, 125/516, 319/516, 39/43],
 [1, -157/516, 77/1032, 125/516, 50/129, 39/43],
 [1, -157/516, 311/516, 125/516, 50/129, 39/43],
 [1, -157/516, 311/516, 311/516, 50/129, 39/43],
 [1, -157/516, 77/1032, 311/516, 50/129, 39/43],
 [1, -157/516, 77/1032, 311/516, 91/516, 39/43],
 [1, -157/516, 311/516, 311/516, 91/516, 39/43],
 [1, -157/516, 77/1032, 125/516, 0, 39/43],
 [1, -157/516, 311/516, 55/129, 0, 39/43],
 [1, -157/516, 311/516, 125/516, 0, 39/43],
 [1, -157/516, 77/1032, 55/129, 0, 39/43]]
```

**Comment by sophiasage** [comment]
Here is the data of the normaliz cone:
```
sage: print(p._normaliz_format(p._get_nmzcone_data()))
amb_space 5
cone 70
 -314 77 250 0 936
 -314 77 250 400 936
 -314 77 440 0 936
 -314 77 622 182 936
 -314 77 622 400 936
 -314 622 250 0 936
 -314 622 250 400 936
 -314 622 440 0 936
 -314 622 622 182 936
 -314 622 622 400 936
 -162 774 250 0 936
 -162 774 440 0 936
 -134 77 802 362 936
 -134 77 802 580 936
 -76 77 250 638 936
 -76 860 250 638 936
 250 1186 250 412 936
 250 1186 250 638 936
 299 77 625 1013 936
 299 77 802 1013 936
 310 1246 310 472 936
 310 1246 310 698 936
 310 1246 636 1024 936
 310 1246 912 472 936
 310 1246 1246 806 936
 310 1246 1246 1024 936
 347 77 250 0 936
 347 77 250 638 936
 347 77 440 0 936
 347 77 625 1013 936
 347 77 802 362 936
 347 77 802 1013 936
 364 575 1300 860 936
 364 575 1300 1078 936
 364 1246 1300 860 936
 364 1246 1300 1078 936
 395 125 250 0 936
 395 125 440 0 936
 395 774 250 0 936
 395 774 440 0 936
 571 349 897 1285 936
 571 349 1074 1285 936
 571 575 1300 1285 936
 571 1246 897 1285 936
 571 1246 1300 1285 936
 604 334 250 209 936
 604 334 250 638 936
 604 983 250 209 936
 604 1186 250 412 936
 604 1186 250 638 936
 619 349 897 1285 936
 619 349 1074 1285 936
 664 1246 310 472 936
 664 1246 310 698 936
 845 575 1300 860 936
 845 575 1300 1285 936
 867 1246 513 472 936
 867 1246 912 472 936
 1251 981 897 1285 936
 1251 1246 897 1285 936
 1255 985 1300 860 936
 1255 1246 1300 860 936
 1504 1234 1150 1109 936
 1504 1234 1150 1285 936
 1504 1234 1300 1109 936
 1504 1234 1300 1285 936
 1504 1246 1150 1109 936
 1504 1246 1150 1285 936
 1504 1246 1300 1109 936
 1504 1246 1300 1285 936
inhom_equations 1
 0 0 0 0 1 -936
inhom_inequalities 20
 -1 0 0 0 0 1504
 -1 0 0 1 0 395
 -1 0 1 0 0 354
 -1 1 0 0 0 270
 0 -1 0 0 0 1246
 0 -1 0 1 0 774
 0 -1 1 0 0 936
 0 0 -1 0 0 1300
 0 0 -1 1 0 440
 0 0 0 -1 0 1285
 0 0 0 1 0 0
 0 0 1 -1 0 388
 0 0 1 0 0 -250
 0 1 -1 0 0 725
 0 1 0 -1 0 936
 0 1 0 0 0 -77
 1 -1 0 0 0 936
 1 0 -1 0 0 936
 1 0 0 -1 0 714
 1 0 0 0 0 314
subspace 0
vertices 0
```

**Comment by w-bruns** [comment]
I computed the Ehrhart series of your polytope on my PC (16 threads) in about 12 hours. No overflow. Result:

```
size of triangulation   = 515
resulting sum of |det|s = 14053361269728

dehomogenization:
0 0 0 0 0 1 


Ehrhart series:
1 587734687349 6447643914520 6434596972453 583385695405 
denominator with 5 factors:
1: 5  

degree of Ehrhart Series as rational function = -1

Ehrhart polynomial:
6 16895 20830839 13046958952 3513340317432 
with common denominator = 6
```
The olytope has 70 vertices and 20 facets. There are 587,734,687,354 lattice points in the polytope. So it is better not to compute them. (The number is derived from the Ehrhart series.)

So this polytope should not have caused the overflow. After looking at the code again, I now think that the 21-digit number that could not be converted is the lattice normalized volume of a simplex in the triangulation of a certain polytope. The bound is 2^63-1. Even if Normaliz would not throw an overflow exception for that simplex, the computation would take 10^6 days or so with the current algorithm.

**Comment by sophiasage** [comment]
That is great! I will try rerunning the computation with an increased time limit, and I'll add in something so that if another overflow appears I'll know exactly which polytope it is. Hopefully the only problem is my own impatience. Half of the polytopes I was running the computation for finished in under two minutes. Thank you for all of your help!

**Comment by sophiasage** [comment]
> After looking at the code again, I now think that the 21-digit number that could not be converted is the lattice normalized volume of a simplex in the triangulation of a certain polytope. 
Where does this come into play?

**Comment by w-bruns** [comment]
Normaliz computes the Ehrhart series by generating the lattice points in the fundamental parallelepipeds defined the by the simplices in the triangulation. Their number is exactly the lattice normalized volume of the simplex.

**Comment by sophiasage** [comment]
I see. Another related question, for about half of the polytopes, the Ehrhart series was computed in under 10 minutes (for example the polytope below). Do you know why this would be? Are there cases where it is quicker to find the lattice points in a fundamental parallelepiped?
```
sage: p.vertices()
(A vertex at (12, 12, 43, 0, 114),
 A vertex at (12, 12, 43, 18, 114),
 A vertex at (12, 12, 83, 0, 114),
 A vertex at (12, 12, 83, 18, 114),
 A vertex at (12, 114, 43, 0, 114),
 A vertex at (12, 114, 83, 0, 114),
 A vertex at (12, 126, 43, 12, 114),
 A vertex at (12, 126, 43, 18, 114),
 A vertex at (12, 126, 83, 12, 114),
 A vertex at (12, 126, 83, 18, 114),
 A vertex at (43, 157, 43, 43, 114),
 A vertex at (43, 157, 43, 49, 114),
 A vertex at (49, 12, 43, 55, 114),
 A vertex at (49, 157, 43, 55, 114),
 A vertex at (102, 12, 96, 108, 114),
 A vertex at (102, 12, 173, 108, 114),
 A vertex at (108, 12, 43, 0, 114),
 A vertex at (108, 12, 43, 55, 114),
 A vertex at (108, 12, 179, 0, 114),
 A vertex at (108, 12, 179, 108, 114),
 A vertex at (108, 114, 43, 0, 114),
 A vertex at (108, 157, 43, 43, 114),
 A vertex at (108, 157, 43, 55, 114),
 A vertex at (120, 12, 55, 0, 114),
 A vertex at (120, 12, 55, 67, 114),
 A vertex at (120, 12, 96, 108, 114),
 A vertex at (120, 12, 179, 0, 114),
 A vertex at (120, 12, 179, 108, 114),
 A vertex at (120, 24, 191, 0, 114),
 A vertex at (120, 114, 191, 0, 114),
 A vertex at (132, 24, 191, 0, 114),
 A vertex at (163, 67, 234, 43, 114),
 A vertex at (163, 67, 234, 163, 114),
 A vertex at (163, 73, 234, 169, 114),
 A vertex at (163, 157, 234, 43, 114),
 A vertex at (163, 277, 234, 163, 114),
 A vertex at (163, 277, 234, 169, 114),
 A vertex at (175, 67, 234, 43, 114),
 A vertex at (175, 67, 234, 163, 114),
 A vertex at (181, 295, 181, 181, 114),
 A vertex at (181, 295, 181, 187, 114),
 A vertex at (181, 295, 234, 181, 114),
 A vertex at (181, 295, 234, 187, 114),
 A vertex at (187, 295, 181, 193, 114),
 A vertex at (204, 114, 198, 210, 114),
 A vertex at (204, 114, 234, 210, 114),
 A vertex at (204, 295, 198, 210, 114),
 A vertex at (204, 295, 234, 210, 114),
 A vertex at (216, 108, 151, 0, 114),
 A vertex at (216, 108, 191, 0, 114),
 A vertex at (216, 114, 151, 0, 114),
 A vertex at (216, 114, 191, 0, 114),
 A vertex at (222, 114, 198, 210, 114),
 A vertex at (222, 114, 234, 210, 114),
 A vertex at (228, 120, 163, 12, 114),
 A vertex at (228, 120, 163, 175, 114),
 A vertex at (228, 120, 198, 210, 114),
 A vertex at (228, 120, 203, 12, 114),
 A vertex at (228, 120, 234, 43, 114),
 A vertex at (228, 120, 234, 210, 114),
 A vertex at (228, 126, 163, 12, 114),
 A vertex at (228, 126, 203, 12, 114),
 A vertex at (228, 157, 234, 43, 114),
 A vertex at (228, 277, 163, 163, 114),
 A vertex at (228, 277, 163, 175, 114),
 A vertex at (228, 295, 181, 181, 114),
 A vertex at (228, 295, 181, 193, 114),
 A vertex at (228, 295, 198, 210, 114),
 A vertex at (228, 295, 234, 181, 114),
 A vertex at (228, 295, 234, 210, 114))
sage: %time p.ehrhart_series()
CPU times: user 8min 22s, sys: 4.65 s, total: 8min 26s
Wall time: 8min 36s
(358931056*t^4 + 4019475493*t^3 + 4073730646*t^2 + 377017989*t + 1)/(-t^5 + 5*t^4 - 10*t^3 + 10*t^2 - 5*t + 1)
```

**Comment by w-bruns** [comment]
It is only a question of number, as long as the dimension and the combinatorial structure don't change. Perhaps we will have another algorithm later this year, but it is unclear whether it can help with polytopes of this kind.

I will run the second example.
