### ISSUE TITLE
EuclideanVolume fails

### ISSUE THREAD

**Issue by videlec** [Normaliz/PyNormaliz#22]
```
>>> import PyNormaliz
>>> square = PyNormaliz.Cone(vertices=[[0,0,1],[1,0,1],[0,1,1],[1,1,1]])
>>> square.EuclideanVolume()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/sage/local/lib/python2.7/site-packages/PyNormaliz.py", line 72, in EuclideanVolume
    return PyNormaliz_cpp.NmzGetEuclideanVolume(self.cone)
AttributeError: 'module' object has no attribute 'NmzGetEuclideanVolume'
```

**Comment by sebasguts** [comment]
The function `NmzGetEuclideanVolume` was removed, `EuclideanVolume` can now be obtained by using `NmzResult`. I will leave this issue open until the `Cone` class is overhauled.
